# Generated by Django 3.0.3 on 2020-03-03 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('register_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(1, 'CDD'), (2, 'CDI'), (3, 'Interim'), (4, 'Freelance')], max_length=100)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('salaire_max', models.IntegerField(blank=True)),
                ('salaire_min', models.IntegerField(blank=True)),
                ('posteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='princ.Compte')),
            ],
        ),
    ]
