# Generated by Django 3.0.3 on 2020-03-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Interim', 'Interim'), ('Freelance', 'Freelance')], max_length=100),
        ),
    ]
