# Generated by Django 3.0.3 on 2020-03-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princ', '0002_auto_20200303_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salaire_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaire_min',
            field=models.IntegerField(null=True),
        ),
    ]
