# Generated by Django 3.0.3 on 2020-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princ', '0004_auto_20200304_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='img_profil',
            field=models.FileField(default='img/svg_icon/1.svg', upload_to='img/candiateds'),
        ),
    ]
