# Generated by Django 3.0.3 on 2020-03-04 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('princ', '0006_candidat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='compte',
        ),
        migrations.AddField(
            model_name='candidat',
            name='img_profile',
            field=models.ImageField(blank=True, default='img/candiateds/8.png', upload_to='img/candiateds/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compte',
            name='img_profil',
            field=models.FileField(default='img/svg_icon/1.svg', upload_to='img/brand/'),
        ),
    ]
