# Generated by Django 3.0.3 on 2020-03-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('princ', '0007_auto_20200304_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='description',
            field=models.TextField(default='vide'),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='princ.Candidat')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='princ.Job')),
            ],
        ),
    ]
