# Generated by Django 3.0.3 on 2020-03-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princ', '0008_auto_20200307_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='proposition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apply',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
